{% set name = "jsonschema-path" %}
{% set version = "0.3.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/p1c2u/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: 71b7e165c7ee86c346593e2ac21b5beafc9bbaac337ef053df028e8827469950

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --ignore-installed --no-build-isolation
  skip: True # [py<38]

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python
  run:
    - pathable >=0.4.1,<0.5.0
    - python
    - pyyaml >=5.1
    - referencing <0.37.0
    - requests <3.0.0,>=2.31.0

test:
  source_files:
    - tests
    - pyproject.toml
  imports:
    - jsonschema_path
  commands:
    - pip check
    - pytest -v tests/unit
  requires:
    - pip
    - pytest
    - pytest-cov >=5.0.0
    - responses >=0.25.0

about:
  home: https://github.com/p1c2u/jsonschema-path
  description: |
    JSONSchema Spec with object-oriented paths
    - Traverse schema like paths
    - Access schema on demand with separate dereferencing accessor layer
  summary: JSONSchema Spec with object-oriented paths
  license: Apache-2.0
  license_file: LICENSE
  license_family: Apache
  dev_url: https://github.com/p1c2u/jsonschema-path
  doc_url: https://github.com/p1c2u/jsonschema-path/blob/main/README.rst

extra:
  recipe-maintainers:
    - bollwyvl